allFood = 
{	
	--gears = true,
--winter food
	winter_food1 = true,
	winter_food2 = true,
	winter_food3 = true,
	winter_food4 = true,
	winter_food5 = true,
	winter_food6 = true,
	winter_food7 = true,
	winter_food8 = true,
	winter_food9 = true,
--halloween food
	halloweencandy_1 = true,
	halloweencandy_2 = true,
	halloweencandy_3 = true,
	halloweencandy_4 = true,
	halloweencandy_5 = true,
	halloweencandy_6 = true,
	halloweencandy_7 = true,
	halloweencandy_8 = true,
	halloweencandy_9 = true,
	halloweencandy_10 = true,
	halloweencandy_11 = true,
--farm food
	eggplant = true,	
	eggplant_cooked = true,	
	corn = true,	
	corn_cooked = true,	
	pumpkin = true,	
	pumpkin_cooked = true,	
	watermelon = true,	
	watermelon_cooked = true,	
	pomegranate = true,	
	pomegranate_cooked = true,	
	durian = true,	
	durian_cooked = true,	
	dragonfruit = true,	
	dragonfruit_cooked = true,	
	carrot = true,
	carrot_cooked = true,	
	potato = true,
	potato_cooked = true,	
	tomato = true,
	tomato_cooked = true,	
	onion = true,
	onion_cooked = true,	
	garlic = true,
	garlic_cooked = true,	
	pepper = true,
	pepper_cooked = true,	
	kelp = true,
	kelp_cooked = true,	
	asparagus = true,
	asparagus_cooked = true,	
	rock_avocado_fruit_ripe = true,
	rock_avocado_fruit_ripe_cooked = true,	
--seeds
	seeds = true,	
	seeds_cooked = true,	
	carrot_seeds = true,	
	eggplant_seeds = true,	
	pumpkin_seeds = true,	
	watermelon_seeds = true,	
	pomegranate_seeds = true,	
	durian_seeds = true,	
	dragonfruit_seeds = true,	
	corn_seeds = true,	
	tomato_seeds = true,
	potato_seeds = true,
	asparagus_seeds = true,
	onion_seeds = true,
	garlic_seeds = true,
	pepper_seeds = true,
--ice
	ice = true,	
--meat+eggs
	meat = true,	
	cookedmeat = true,	
	meat_dried = true,		
	monstermeat = true,	
	cookedmonstermeat = true,	
	monstermeat_dried = true,	
	plantmeat = true,	
	plantmeat_cooked = true,	
	smallmeat = true,	
	cookedsmallmeat = true,	
	smallmeat_dried = true,	
	drumstick = true,	
	drumstick_cooked = true,		
	fishmeat = true,	
	fishmeat_cooked	= true,	
	fishmeat_small = true,	
	fishmeat_small_cooked	= true,	
	eel = true,	
	eel_cooked = true,		
	froglegs = true,	
	froglegs_cooked = true,		
	batwing = true,	
	batwing_cooked = true,		
	trunk_cooked = true,	
	trunk_summer = true,	
	trunk_winter = true,	
	tallbirdegg = true,	
	tallbirdegg_cooked = true,
	tallbirdegg_cracked = true,		
	minotaurhorn = true,	
	deerclops_eyeball = true,		
	bird_egg = true,	
	bird_egg_cooked = true,	
	humanmeat_cooked = true,
	humanmeat_dried = true,
	humanmeat = true,
--veggies+mushrooms+berries+misc
	royal_jelly = true,
	phlegm = true,
	glommerfuel = true,
	butter = true,	
	goatmilk = true,	
	honey = true,	
	red_cap = true,	
	red_cap_cooked = true,	
	blue_cap = true,	
	blue_cap_cooked = true,	
	green_cap = true,	
	green_cap_cooked = true,	
	mandrake = true,	
	cookedmandrake = true,	
	wormlight = true,	
	wormlight_lesser = true,	
	cutlichen = true,	
	cactus_meat = true,	
	cactus_meat_cooked = true,	
	cactus_flower = true,		
	berries = true,	
	berries_cooked = true,	
	cave_banana_cooked = true,	
	cave_banana = true,	
	berries_juicy = true,	
	berries_juicy_cooked = true,	 	
	butterflywings = true,	
	acorn_cooked = true,	
--crockpot	
	baconeggs = true,	
	butterflymuffin = true,	
	dragonpie = true,	
	fishtacos = true,	
	fishsticks = true,	
	jammypreserves = true,	
	flowersalad = true,	
	frogglebunwich = true,	
	fruitmedley = true,	
	guacamole = true,	
	honeyham = true,	
	honeynuggets = true,	
	icecream = true,	
	jellybean = true,	
	kabobs = true,	
	mandrakesoup = true,	
	meatballs = true,	
	bonestew = true,	
	watermelonicle = true,	
	monsterlasagna = true,	
	perogies = true,	
	powcake = true,	
	pumpkincookie = true,	
	ratatouille = true,		
	hotchili = true,	
	stuffedeggplant = true,	
	taffy = true,	
	trailmix = true,	
	turkeydinner = true,	
	unagi = true,	
	waffles = true,	
	potatotornado = true,	
	mashedpotatoes = true,	
	asparagussoup = true,	
	vegstinger = true,	
	bananapop = true,	
	ceviche = true,	
	salsa = true,	
	pepperpopper = true,	
	nightmarepie = true,	
	voltgoatjelly = true,	
	glowberrymousse = true,	
	frogfishbowl = true,	
	dragonchilisalad = true,	
	gazpacho = true,	
	potatosouffle = true,	
	monstertartare = true,	
	freshfruitcrepes = true,	
	bonesoup = true,	
	moqueca = true,	
	surfnturf = true,
	californiaroll = true,
	seafoodgumbo = true,
	moonbutterflywings = true,
	moon_tree_blossom = true,
}

orderedFood = 
{
--farm food
	eggplant=1,	
	eggplant_cooked=2, 	
	corn=3, 	
	corn_cooked=4, 	
	pumpkin=5,	
	pumpkin_cooked=6, 
	watermelon=7,	
	watermelon_cooked=8,	
	pomegranate=9, 	
	pomegranate_cooked=10, 	
	durian=11, 
	durian_cooked=12, 
	dragonfruit=13, 	
	dragonfruit_cooked=14, 
	carrot=15, 
	carrot_cooked=16, 	
--meat+eggs
	meat=17, 	
	cookedmeat=18, 
	meat_dried=19, 		
	monstermeat=20,	
	cookedmonstermeat=21, 	
	monstermeat_dried=22,		
	smallmeat=23, 	
	cookedsmallmeat=24, 	
	smallmeat_dried=25, 	
	drumstick=26, 	
	drumstick_cooked=27, 		
	fishmeat_small=28, 	
	fishmeat_small_cooked=29,			
	froglegs=30, 	
	froglegs_cooked=31, 				
	trunk_cooked=32, 
	trunk_summer=33, 		
	tallbirdegg=34, 	
	tallbirdegg_cooked=35, 				
	bird_egg=36, 	
	bird_egg_cooked=37, 	
--veggies+mushrooms+berries+misc
	fish=38,
	butter=39, 	
	goatmilk=40, 	
	honey=41, 	
	red_cap=42, 	
	red_cap_cooked=43, 	
	blue_cap=44, 	
	blue_cap_cooked=45, 	
	green_cap=46, 	
	green_cap_cooked=47, 	
	cactus_meat=48, 	
	cactus_meat_cooked=49, 			
	butterflywings=50, 	
	acorn_cooked=51, 	
--crockpot	
	baconeggs=52, 
	butterflymuffin=53, 	
	dragonpie=54, 
	fishtacos=55,	
	fishsticks=56, 
	jammypreserves=57, 	
	frogglebunwich=58, 
	fruitmedley=59, 
	guacamole=60, 	
	honeyham=61, 	
	honeynuggets=62, 	
	icecream=63, 	
	kabobs=64,  	
	meatballs=65, 
	bonestew=66, 
	watermelonicle=67,
	monsterlasagna=68, 
	perogies=69, 	
	powcake=70, 	
	pumpkincookie=71, 
	ratatouille=72, 
	hotchili=73, 
	stuffedeggplant=74, 
	taffy=75,
	trailmix=76, 
	turkeydinner=77,  
	waffles=78,
	mandrake=79, 	
	cookedmandrake=80, 	
	mandrakesoup=81,
	plantmeat=82, 
	plantmeat_cooked=83,
	trunk_winter=84, 
	flowersalad=85,
	cactus_flower=86,	
	deerclops_eyeball=87,
	jellybean=88, 
	batwing=89, 	 
	batwing_cooked=90,
	eel=91, 	
	eel_cooked=92, 
	minotaurhorn=93, 
 	wormlight=94, 	
	wormlight_lesser=95,	
	cutlichen=96,
	cave_banana_cooked=97, 
	cave_banana=98,
	unagi=99,
	gears=100,
	salsa=101,
	potato=102,
	potato_cooked=103,
	tomato=104,
	tomato_cooked=105,
	garlic=106,
	garlic_cooked=107,
	onion=108,
	onion_cooked=109,
	asparagus=110,
	asparagus_cooked=111,
	pepper=112,
	pepper_cooked=113,
	potatotornado = 114,	
	mashedpotatoes = 115,	
	asparagussoup = 116,	
	vegstinger = 117,	
	ceviche = 118,	
	salsa = 119,	
	pepperpopper = 120,
	surfnturf = 121,
}

allFoodsRare =
{
	"mandrake", 	
	"cookedmandrake", 	
	"mandrakesoup",
}

allFoodsLongterm =
{
	"plantmeat", 
	"plantmeat_cooked",
	"trunk_winter", 
	"flowersalad",
	"cactus_flower",	
	--"deerclops_eyeball",
}	

allFoodsHard =
{
	"jellybean", 
	"icecream", 
	"butter", 	
	"goatmilk", 	
	"waffles",	
}	

allFoodsCave =
{
	"batwing", 	 
	"batwing_cooked",
	"eel", 	
	"eel_cooked", 
	--"minotaurhorn", 
 	"wormlight", 	
	"wormlight_lesser",	
	"cutlichen",
	"cave_banana_cooked", 
	"cave_banana",
	"unagi",
}		

allFoods = 
{	
--farm food
	"potato",
	"potato_cooked",
	"tomato",
	"tomato_cooked",
	"onion",
	"onion_cooked",
	"garlic",
	"garlic_cooked",
	"pepper",
	"pepper_cooked",
	"asparagus",
	"asparagus_cooked",
	"eggplant",	
	"eggplant_cooked", 	
	"corn", 	
	"corn_cooked", 	
	"pumpkin",	
	"pumpkin_cooked", 
	"watermelon",	
	"watermelon_cooked",	
	"pomegranate", 	
	"pomegranate_cooked", 	
	"durian", 
	"durian_cooked", 
	"dragonfruit", 	
	"dragonfruit_cooked", 
	"carrot", 
	"carrot_cooked", 	
--meat+eggs
	"meat", 	
	"cookedmeat", 
	"meat_dried", 		
	"monstermeat",	
	"cookedmonstermeat", 	
	"monstermeat_dried",		
	"smallmeat", 	
	"cookedsmallmeat", 	
	"smallmeat_dried", 	
	"drumstick", 	
	"drumstick_cooked", 		
	"fishmeat_small", 	
	"fishmeat_small_cooked",			
	"froglegs", 	
	"froglegs_cooked", 				
	"trunk_cooked", 
	"trunk_summer", 		
	"tallbirdegg", 	
	"tallbirdegg_cooked", 				
	"bird_egg", 	
	"bird_egg_cooked", 	
--veggies+mushrooms+berries+misc
	"honey", 	
	"red_cap", 	
	"red_cap_cooked", 	
	"blue_cap", 	
	"blue_cap_cooked", 	
	"green_cap", 	
	"green_cap_cooked", 	
	"cactus_meat", 	
	"cactus_meat_cooked", 			
	"butterflywings", 	
	"acorn_cooked", 	
--crockpot	
	"baconeggs", 
	"butterflymuffin", 	
	"dragonpie", 
	"fishtacos",	
	"fishsticks", 
	"jammypreserves", 	
	"frogglebunwich", 
	"fruitmedley", 
	"guacamole", 	
	"honeyham", 	
	"honeynuggets", 	
	"kabobs",  	
	"meatballs", 
	"bonestew", 
	"watermelonicle",
	"monsterlasagna", 
	"perogies", 	
	"powcake", 	
	"pumpkincookie", 
	"ratatouille", 
	"hotchili", 
	"stuffedeggplant", 
	"taffy",
	"trailmix", 
	"turkeydinner", 
	"potatotornado",	
	"mashedpotatoes",	
	"asparagussoup",	
	"vegstinger",	
	"ceviche",	
	"salsa",	
	"pepperpopper",
	"surfnturf",
}

crockpotHard =
{
	"jellybean",
	"icecream",
	"waffles",	
}

crockpotCave =
{
	"unagi",
}

crockpotRare =
{
	"mandrakesoup",
}

crockpotLongterm =
{
	"flowersalad",
}

crockpotFood = 
{
	"baconeggs",	
	"butterflymuffin",	
	"dragonpie",	
	"fishtacos",	
	"fishsticks",	
	"jammypreserves",	
	"frogglebunwich",	
	"fruitmedley",	
	"guacamole",	
	"honeyham",	
	"honeynuggets",		
	"kabobs",	
	"meatballs",	
	"bonestew",	
	"watermelonicle",	
	"monsterlasagna",	
	"perogies",	
	"powcake",	
	"pumpkincookie",	
	"ratatouille",	
	"hotchili",	
	"stuffedeggplant",	
	"taffy",	
	"trailmix",	
	"turkeydinner",	
	"potatotornado",	
	"mashedpotatoes",	
	"asparagussoup",	
	"vegstinger",	
	"ceviche",	
	"salsa",	
	"pepperpopper",
	"surfnturf",
}

wigfridLongterm =
{
	"plantmeat", 	
	"plantmeat_cooked",
	--"deerclops_eyeball", 
	"trunk_winter", 	
}

wigfridCave =
{
	"eel", 
	"eel_cooked", 
	"batwing", 
	"batwing_cooked",
	--"minotaurhorn", 
}

wigfridFood =
{
	"meat",	
	"cookedmeat", 	
	"meat_dried", 		
	"monstermeat",	
	"cookedmonstermeat",	
	"monstermeat_dried",	
	"smallmeat", 	
	"cookedsmallmeat",	
	"smallmeat_dried",	
	"drumstick",	
	"drumstick_cooked",		
	"fishmeat_small", 
	"fishmeat_small_cooked",				
	"froglegs",	
	"froglegs_cooked", 				
	"trunk_cooked", 
	"trunk_summer", 
	"tallbirdegg", 
	"tallbirdegg_cooked",				
	"bird_egg", 
	"bird_egg_cooked", 
}

wurtFood =
{
	"eggplant",	
	"eggplant_cooked", 	
	"corn", 	
	"corn_cooked", 	
	"pumpkin",	
	"pumpkin_cooked", 
	"watermelon",	
	"watermelon_cooked",	
	"pomegranate", 	
	"pomegranate_cooked", 	
	"durian", 
	"durian_cooked", 
	"dragonfruit", 	
	"dragonfruit_cooked", 
	"carrot", 
	"carrot_cooked", 	
--veggies+mushrooms+berries+misc
	"honey", 	
	"red_cap", 	
	"red_cap_cooked", 	
	"blue_cap", 	
	"blue_cap_cooked", 	
	"green_cap", 	
	"green_cap_cooked", 	
	"cactus_meat", 	
	"cactus_meat_cooked", 			
	"butterflywings", 	
	"acorn_cooked",
	"potato",
	"potato_cooked",
	"tomato",
	"tomato_cooked",
	"onion",
	"onion_cooked",
	"garlic",
	"garlic_cooked",
	"pepper",
	"pepper_cooked",
	"asparagus",
	"asparagus_cooked", 	
}

wigfridCrockpotCave =
{
	"unagi", 
}

wigfridCrockpot =
{
	"baconeggs",
	"frogglebunwich", 
	"guacamole",
	"honeyham", 
	"honeynuggets", 
	"kabobs", 
	"meatballs", 
	"bonestew", 
	"monsterlasagna", 
	"perogies", 
	"hotchili", 
	"turkeydinner", 
	"ceviche",
	"pepperpopper",
	"surfnturf",
}

wurtCrockpot =
{
	"butterflymuffin", 	
	"dragonpie", 
	"jammypreserves", 	
	"fruitmedley", 
	"watermelonicle",
	"powcake", 	
	"pumpkincookie", 
	"ratatouille", 
	"stuffedeggplant", 
	"taffy",
	"trailmix", 
	"potatotornado",	
	"mashedpotatoes",	
	"asparagussoup",	
	"vegstinger",	
	"salsa",	
}

wxFood = 
{
	"gears",
}
